name: Create Image Pipeline

on:
  workflow_dispatch: # Ejecuta por solicitud manual
permissions:
  contents: read
  packages: write

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Maven verify (lint + compile)
        run: mvn -B -DskipTests verify

  dummy-tests:
    name: Run Dummy Tests
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run only dummy test
        run: mvn -B test -Dtest=DummyTest

  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: dummy-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Creamos el nombre en minúsculas y lo guardamos bien
      - name: Set lowercase repository name
        id: prep
        run: |
          REPO_LOWER=$(echo "ghcr.io/${{ github.repository_owner }}/app_gestionusuarios" | tr '[:upper:]' '[:lower:]')
          echo "image_path=${REPO_LOWER}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Usamos el "output" del paso anterior para construir
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Usamos 'steps.prep.outputs.image_path' que es más fiable que env
          tags: |
            ${{ steps.prep.outputs.image_path }}:1.0
            ${{ steps.prep.outputs.image_path }}:latest
            ${{ steps.prep.outputs.image_path }}:${{ github.sha }}